### ISSUE TITLE
Add environment variables for disabling case sensitivity and unicode mode.

### ISSUE THREAD

**Issue by pbrubaker** [derkork/perforce-mini#2]
These are important settings for clients interacting from Windows, it would be great to have them as environment settings in the `docker_compose.yml` file.

Case sensitivity can be disabled with the `-C1` command line parameter.

Maybe it would be good to have a environment variable that just appends to the command line and remove these CLI options from the built in command line?

**Comment by derkork** [comment]
You can now use `PERFORCE_SETUP_OPTS` to provide additional options for first-time setup and `PERFORCE_SERVER_OPTS` to provide additional options for p4d. I have added documentation to the README file as well.
